site_app/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetalheView.as_view(), name='detalhe'),
    path('<int:pk>/resultados/', views.ResultadosView.as_view(), name='resultados'),
    path('<int:pergunta_id>/voto/', views.voto, name='voto'),
]

site_app/site_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

site_app/app/models.py
from django.db import models


# Create your models here.
class Pergunta(models.Model):
    pergunta_text = models.CharField(max_length=200)
    data_public = models.DateTimeField('Data de publicação')

    def __str__(self):
        return self.pergunta_text


class Resposta(models.Model):
    resposta_text = models.CharField(max_length=200)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.resposta_text

site_app/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Pergunta, Resposta


class IndexView(ListView):
    template_name = 'app/index.html'
    context_object_name = 'final_lista_pergunta'

    def get_queryset(self):
        """ Retornando as 10 últimas perguntas publicadas """
        return Pergunta.objects.order_by('-data_public')[:10]


class DetalheView(DetailView):
    model = Pergunta
    template_name = 'app/detalhe.html'


class ResultadosView(DetalheView):
    model = Pergunta
    template_name = 'app/resultados.html'


def voto(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        selecao_resposta = pergunta.resposta_set.get(pk=request.POST['resposta'])
    except (KeyError, Resposta.DoesNotExist):
        return render(request, 'app/detalhe.html', {
            'pergunta': pergunta,
            'mensagem_erro': 'Você não selecionou uma resposta'
        })
    else:
        selecao_resposta.votos += 1
        selecao_resposta.save()
        return HttpResponseRedirect(reverse('app:resultados', args=(pergunta.id,)))

site_app/app/templates/app/detalhe.html
<form action="{% url 'app:voto' pergunta.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ resposta.resposta_text }}</h1></legend>
        {% if mensagem_erro %}
            <p>
                <strong>{{ mensagem_erro }}</strong>
            </p>
        {% endif %}
        {% for resposta in pergunta.resposta_set.all %}
            <input type="radio" name="resposta" id="resposta{{ forloop.counter }}" value="{{ resposta.id }}">
            <label for="resposta{{ forloop.counter }}">{{ resposta.resposta_text }}</label>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Voto">
</form>

site_app/app/templates/app/index.html
{% if final_lista_pergunta %}
    <ul>
        {% for pergunta in final_lista_pergunta %}
            <li>
                <a href="{% url 'app:detalhe' pergunta.id %}">{{ pergunta.pergunta_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Não há perguntas disponíveis</p>
{% endif %}

site_app/app/templates/app/resultados.html
<h1>{{ pergunta.pergunta_text }}</h1>
<ul>
    {% for resposta in pergunta.resposta_set.all %}
        <li>{{ resposta.resposta_text }} -- {{ resposta.votos }} voto{{ resposta.votos|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'app:detalhe' pergunta.id %}">Vote novamente</a>